version: "3.7"

services:
  php:
    build:
      # Dockerfile
      context: ./docker/
    volumes:
      # путь к проектам
      - ./:/var/www/html/fias/
      - ./tmp/:/tmp/
    environment:
      XDEBUG_CONFIG: remote_host=host.docker.internal remote_port=9000 remote_enable=1 remote_autostart=1 remote_handler=dbgp remote_connect_back=0